family_tab<-table(titanic$Family)
barplot(family_tab)
install.packages("titanic")
library("titanic")
install.packages("mice")
library("mice")
sum(is.na(titanic_train$Age))
mice_imputes = mice(titanic_train, m=5, maxit = 40)
 Imputed=complete(mice_imputes, 5)
hist(titanic_train$Age, main = "Actual Data", col = "Blue")
hist(Imputed$Age, main = "Imputed Data", col ="Red")
